### ISSUE TITLE
Error adding glusterfs3.5

### ISSUE THREAD

**Issue by andybrown668** [geerlingguy/ansible-role-glusterfs#16]
I get this error when adding your role to a server - it looks like an issue with a missing Release file in the 3.5 ppa. Changing `glusterfs_ppa_version` from 3.5 to 3.8 gets around the issue

`TASK [geerlingguy.glusterfs : Add PPA for GlusterFS.] **************************
fatal: [site02]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_ezhESi/ansible_module_apt_repository.py\", line 522, in <module>\r\n    main()\r\n  File \"/tmp/ansible_ezhESi/ansible_module_apt_repository.py\", line 512, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:The repository 'http://ppa.launchpad.net/gluster/glusterfs-3.5/ubuntu xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://ppa.launchpad.net/gluster/glusterfs-3.5/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE", "parsed": false}
`

**Comment by geerlingguy** [comment]
This was fixed in https://github.com/geerlingguy/ansible-role-glusterfs/pull/18 — I'm testing then will add another release shortly.
