### ISSUE TITLE
GlusterFS role Debian installs fail

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-glusterfs#20]
See builds: https://travis-ci.org/geerlingguy/ansible-role-glusterfs/builds/272741717

Basically, we need to follow the directions here:

  - https://gluster.readthedocs.io/en/latest/Install-Guide/Install/
  - Or more up to date: https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/

The PPA doesn't install on Debian :P

**Comment by lvnilesh** [comment]
See #22 #22 

What would be the best way to invoke `setup-direct.yml` ?

The below segment works for me when I hack `https://github.com/geerlingguy/ansible-role-glusterfs/blob/master/tasks/main.yml` like this
```
- include: setup-direct.yml
  when: ansible_os_family == 'Debian'
```

**Comment by bdragon28** [comment]
ansible_distribuion == 'Debian'. Ubuntu is still in the Debian OS family so you need to be specific when you are targeting "real" debian.

**Comment by bdragon28** [comment]
Frankly, setup-direct.yml should be setup-Debian.yml and setup-Debian.yml should be setup-Ubuntu.yml, and tasks/main.yml should be checking ansible_distribution instead of ansible_os_family for debian derivitives..

**Comment by bdragon28** [comment]
Also I note that the daemon name changed to 'glusterd' to match Redhat. I assume the ubuntu version did at some point too, if so, the whole dynamic variables thing can go away :)

**Comment by elfshed** [comment]
This makes it work in Debian but it might not be the right way to do it.

```
diff --git a/tasks/setup-Debian.yml b/tasks/setup-Debian.yml
index e156e4b..532ed74 100644
--- a/tasks/setup-Debian.yml
+++ b/tasks/setup-Debian.yml
@@ -5,7 +5,10 @@
     state: present
     update_cache: yes
   register: glusterfs_ppa_added
-  when: glusterfs_ppa_use
+  when:
+    - glusterfs_ppa_use
+    - ansible_distribution=='Ubuntu'
+    - ansible_distribution_major_version <= '16'
 
 - name: Ensure GlusterFS will reinstall if the PPA was just added.
   apt:
```

**Comment by jsenecal** [comment]
Fixing this would mean a great deal to us 👍

**Comment by romaindequidt** [comment]
I've created https://github.com/geerlingguy/ansible-role-glusterfs/pull/26 about that, if needed.

**Comment by geerlingguy** [comment]
@romaindequidt - Ah disregard comment in PR, I should read my own issues :P

**Comment by geerlingguy** [comment]
Works now, see #27
