### ISSUE TITLE
Packages actualization

### ISSUE THREAD

**Issue by seprob** [geerlingguy/ansible-role-glusterfs#24]
Maybe it would be good to switch off GlusterFS pakages upgrading (for example for Ubuntu "apt-mark hold glusterfs*") for security reasons.

**Comment by geerlingguy** [comment]
On Debian/Ubuntu, my recommendation is to configure Apt pinning on your own outside this role if you need refined control over version pinning.

See my Kubernetes role for an example apt pinning configuration: https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/tasks/setup-Debian.yml#L22-L25
