### ISSUE TITLE
New CentOS release 7.6 breaks repo install

### ISSUE THREAD

**Issue by jfarcher** [geerlingguy/ansible-role-glusterfs#29]
With the new CentOS release the installation of the repository package now installs centos-release-gluster-legacy from the extras, which by default which doesn't give access to any gluster packages.

Packages available:

> centos-release-gluster-legacy.noarch : Disable unmaintained Gluster repositories from the CentOS Storage SIG
> centos-release-gluster40.x86_64 : Gluster 4.0 (Short Term Stable) packages from the CentOS Storage SIG repository
> centos-release-gluster41.noarch : Gluster 4.1 (Long Term Stable) packages from the CentOS Storage SIG repository
> centos-release-gluster5.noarch : Gluster 5 packages from the CentOS Storage SIG repository

Looking at the setup-RedHat.yml file it specified centos-release-gluster{{ glusterfs_default_release }} so I guess specifying 40, 41 or 5 should work but in the default file this variable suggests usage is only for Ubuntu.

I fixed this in my env by changing the variable above in the defaults to 41 (LTS repo for Gluster)

Not sure what the best approach would be to resolve this, other than ensure a relevant repo version is specified. Shame CentOS/RHEL don't have a package without version in the title which works.

**Comment by geerlingguy** [comment]
Interesting... I'll have to do a little more testing to see if there's an elegant way to fix that :/
