### ISSUE TITLE
Install fails for Raspberry Pi 3B

### ISSUE THREAD

**Issue by wpoosanguansit** [geerlingguy/ansible-role-glusterfs#33]
Hi,

I am trying to use the role and it fails for Rpi B3+:

TASK [geerlingguy.glusterfs : Ensure debian repo is present.] *********************************************************************************************************************
Sunday 26 January 2020  12:14:12 -0800 (0:00:01.080)       0:03:11.539 ******** 
fatal: [pi1]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

Thanks.

**Comment by geerlingguy** [comment]
@wpoosanguansit - I would suggest attempting to run `apt update` on the Pi itself to see if you can get apt cache to update manually. Maybe there's an issue with apt currently? A reboot might also help.

**Comment by chazragg** [comment]
sorry to bring up an old tickets but i am currently experiencing this issue. i have manually run an apt update on my pi which throws no errors and also rebooted them but this error still persists. could you provide any more insight to this issue ? other roles with update_cache enable do not seem to have this error.

`The full traceback is:
  File "/tmp/ansible_apt_repository_payload_nycaw82d/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 589, in update
    raise FetchFailedException(e)
fatal: [192.168.0.200]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": "gluster",
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [trusted=yes] https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/buster/armhf/apt buster main",
            "state": "present",
            "update_cache": true,
            "validate_certs": true
        }
    },
    "msg": "apt cache update failed"
}`

here is -vvv output from my playbook

`sudo apt update
[sudo] password for chazragg:
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 https://download.docker.com/linux/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.`

and here is the output from sudo apt update from one of my pis

**Comment by chazragg** [comment]
Now that work has calmed down a bit i had the time to look into this a bit more. it seems your role it pulling Glusterfs from the following URL any Rpi

https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/ buster/armhf/ 

which does not appear to exist, it seems glusterFS is only building arm64 and amd64 package for buster. 
i can't see any way around this for now unless the role uses a different package repository but i hope this helps.

**Comment by geerlingguy** [comment]
@chazragg - Can you open a new issue for this problem?
