### ISSUE TITLE
Apt repository specification contains trusted=yes

### ISSUE THREAD

**Issue by apollo13** [geerlingguy/ansible-role-glusterfs#37]
I do not think trusted=yes should be there. After all you are installing the pubkey in https://github.com/geerlingguy/ansible-role-glusterfs/blob/b831a71905ead67dda80d7496505eb350d6497cf/tasks/setup-Debian.yml#L12

The official docs do not recommend [trusted=yes] either: https://docs.gluster.org/en/latest/Install-Guide/Install/

**Comment by apollo13** [comment]
*bump*

**Comment by geerlingguy** [comment]
Done in above commit - thanks for filing the issue!
