### ISSUE TITLE
glusterfs installation fails due to missing python3-pyxattr package

### ISSUE THREAD

**Issue by fgierlinger** [geerlingguy/ansible-role-glusterfs#39]
**Summary**
The installation of glusterfs fails on a fresh CentOS 8 Stream installation with the following error:
```
TASK [geerlingguy.glusterfs : Ensure Gluster packages are installed.]
*******************************************************************************
fatal: [centos8stream]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: 
cannot install the best candidate for the job\n  - nothing provides python3-pyxattr needed by 
glusterfs-server-9.1-1.el8.aarch64", "rc": 1, "results": []}
```

The package `python3-pyxattr` is [provided by the PowerTools repo](https://centos.pkgs.org/8/centos-powertools-x86_64/python3-pyxattr-0.5.3-18.el8.x86_64.rpm.html), which is not activated per default. The repository can be activated with `dnf config-manager --enable PowerTools`

```
[fgierlinger@centos8stream ~]$ sudo dnf repolist
repo id                                                  repo name
AppStream                                                CentOS-8 - AppStream
BaseOS                                                   CentOS-8 - Base
centos-gluster9                                          CentOS-8 - Gluster 9
extras                                                   CentOS-8 - Extras
[fgierlinger@centos8stream ~]$ sudo dnf config-manager --enable PowerTools
[fgierlinger@centos8stream ~]$ sudo dnf repolist
repo id                                                  repo name
AppStream                                                CentOS-8 - AppStream
BaseOS                                                   CentOS-8 - Base
PowerTools                                               CentOS-8 - PowerTools
centos-gluster9                                          CentOS-8 - Gluster 9
extras                                                   CentOS-8 - Extras
```

The parameter `enablerepo` for [yum](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html) might solve this problem, but I have not tested it.

**Steps to reproduce**
Execute the following playbook on a CentOS 8 Stream host.
```
- hosts: all
  gather_facts: yes
  roles:
    - role: geerlingguy.glusterfs
      vars:
        glusterfs_default_release: 9
```

**Expected behaviour**
Glusterfs installation succeeds when executing the role and specifying `glusterfs_default_release: 9`

**Actual behaviour**
The installation of glusterfs fails, because the package `python3-pyxattr` can not be installed, which is located in the PowerTools repository. The PowerTools repository is not enabled in a CentOS 8 Stream minimal installation

**Host information**
OS: CentOS 8 Stream aarch64
Python: 3.8.2
Ansible: 2.10.7
geerlingguy.glusterfs: 3.1.2

**Comment by fgierlinger** [comment]
Still relevant.

**Comment by fgierlinger** [comment]
Still relevant and PR has already been submitted #40

**Comment by geerlingguy** [comment]
Does this fail on `rockylinux8` as well? I'm dropping any official support for Stream in my roles.

**Comment by geerlingguy** [comment]
Just added a `rockylinux8` test; may still fail there, though the way I add `powertools` differs a little bit from the implementation in the PR. https://github.com/geerlingguy/ansible-role-glusterfs/runs/4419995860?check_suite_focus=true
