### ISSUE TITLE
wrong apt repo address for raspberry pi

### ISSUE THREAD

**Issue by yodog** [geerlingguy/ansible-role-glusterfs#43]
```
TASK [geerlingguy.glusterfs : Ensure debian repo is present.] ******************************************************************************************************************************************************************************************************************
fatal: [pi3modelb]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/bullseye/armhf/apt bullseye Release' does not have a Release file."}
```

i believe the right address is `https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/bullseye/arm64/apt/` but its currently empty.

is there any way to ignore this error and move on?

**Comment by geerlingguy** [comment]
If you're running 32-bit Pi OS, then `armhf` would be correct.

**Comment by yodog** [comment]
oh. ok. my mistake.
but there is no armhf directory

**Comment by geerlingguy** [comment]
In that case, it does seem their arm64 directory is empty (https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/bullseye/arm64/apt/), and they don't have a directory for armhf at all (which means it wouldn't support 32-bit Pi OS or Debian on ARM at all, you have to run the 64-bit version).

Looking through all their other directories, it seems like they only have amd64 support right now.

**Comment by geerlingguy** [comment]
Ah... look here: https://github.com/gluster/glusterfs/issues/1301 — seems like a bug after GlusterFS 6 came out.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-role-glusterfs/issues/38
