### ISSUE TITLE
glusterfs EPEL repo urls does not work

### ISSUE THREAD

**Issue by heikkis** [geerlingguy/ansible-role-glusterfs#5]
For example http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo/pub.key does not work. There are http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo/rsa.pub file availible.

File http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo/glusterfs-epel.repo is updated.

**Comment by heikkis** [comment]
See https://github.com/geerlingguy/ansible-role-glusterfs/pull/6

**Comment by geerlingguy** [comment]
Thanks! This is fixed in #6; good catch!
