### ISSUE TITLE
Task: Ensure GlusterFS is installed fails

### ISSUE THREAD

**Issue by pjmaurer** [geerlingguy/ansible-role-glusterfs#8]
It looks like the repo has moved from http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL/ to http://buildlogs.centos.org/centos/7/storage/x86_64/gluster-3.8/

**Comment by geerlingguy** [comment]
Moving further work into https://github.com/geerlingguy/ansible-role-glusterfs/issues/13 (it's now working on some OSes, not others...)
